services:
  - type: web
    name: clipo-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx serve@latest -s dist -l 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://clipo-test-be.onrender.com/api
      - key: VITE_GOOGLE_CLIENT_ID
        value: 602293352058-mv2k3nu25qs51hdsu9iah0hdfnmtrerg.apps.googleusercontent.com

    autoDeploy: true
    plan: starter
